% Auteur : Hugo Therrien
% Date de création : 2017-03-30
% Date d'édition : 2017-03-30
% Description du programme : Programme de generation des graphiques pour
% SM-5


close all;
clc;

dossier = 'images_non_lin';
mkdir images_non_lin

nom_sorties = {'Angle \phi de la plaque',...
               'Angle \theta de la plaque',...
               'position en z de la plaque',...
               '\omega_{\phi} de la plaque',...
               '\omega_{\theta} de la plaque',...
               'v_{z} de la plaque',...
               'position en x de la bille',...
               'position en y de la bille',...
               'vitesse en x de la bille',...
               'vitesse en y de la bille',...
               'Courant de l''actionneur A',...
               'Courant de l''actionneur B',...
               'Courant de l''actionneur C',...
               'Distance en z de la plaque de l''actionneur A',...
               'Distance en z de la plaque de l''actionneur B',...
               'Distance en z de la plaque de l''actionneur C',...
               'Distance en z de la plaque du capteur D',...
               'Distance en z de la plaque du capteur E',...
               'Distance en z de la plaque du capteur F',...
               'Force exercée par l''actionneur A sur la plaque',...
               'Force exercée par l''actionneur B sur la plaque',...
               'Force exercée par l''actionneur C sur la plaque',...
               'Tension de l''actionneur A',...
               'Tension de l''actionneur B',...
               'Tension de l''actionneur C'};
           
nom_fichiers = {'ax_non_lin',...
               'ay_non_lin',...
               'pz_non_lin',...
               'wx_non_lin',...
               'wy_non_lin',...
               'vz_non_lin',...
               'px_non_lin',...
               'py_non_lin',...
               'vx_non_lin',...
               'vy_non_lin',...
               'ia_non_lin',...
               'ib_non_lin',...
               'ic_non_lin',...
               'za_non_lin',...
               'zb_non_lin',...
               'zc_non_lin',...
               'zd_non_lin',...
               'ze_non_lin',...
               'zf_non_lin',...
               'fa_non_lin',...
               'fb_non_lin',...
               'fc_non_lin',...
               'va_non_lin',...
               'vb_non_lin',...
               'vc_non_lin'};
          
for i = 1:size(ynonlineaire_prof,2)
    figure
    hold
    plot(tsim_equipe,ynonlineaire_equipe(:,i));
    plot(tsim_prof,ynonlineaire_prof(:,i));
    title(nom_sorties{i});
    legend('Valeur attendue','Valeur obtenue')
    %N = length(tsim);
    %erms = sqrt(1/N*sum((ynonlineaire_prof(:,i)-ynonlineaire_equipe1(:,i))).^2) 
    %texte_RMS = annotation(['Erreur RMS' erms]);
    %texte_RMS.Position = [0.1 0.9 0.2 0.1];
    print([dossier '\' num2str(i) '. ' nom_fichiers{i} '.png'],'-dpng','-r300')
    close
end;

